#!/usr/local/bin/bash

if ! [ -z "$1" ]; then
    make
    cp $1 expected.txt
    ./encrypt $1
    cp $1 encrypted.txt
    ./decrypt $1
    diff $1 expected.txt
    make clean
else
    echo "Usage: ./test [file path]"
fi
